import type { Rule } from "../policyHelpers";

const sharedGitReadRules: Rule[] = [
  { pattern: "git config --get *", decision: "allow" },
  { pattern: "git config --get-regexp *", decision: "allow" },
  { pattern: "git config --list", decision: "allow" },
  { pattern: "git config --list *", decision: "allow" },
  { pattern: "git config * --list", decision: "allow" },
  { pattern: "git config * --list *", decision: "allow" },
  { pattern: "git config -l", decision: "allow" },
  { pattern: "git config -l *", decision: "allow" },
  { pattern: "git reflog", decision: "allow" },
  { pattern: "git reflog show", decision: "allow" },
  { pattern: "git reflog show *", decision: "allow" },
  { pattern: "git reflog list", decision: "allow" },
  { pattern: "git reflog list *", decision: "allow" },
  { pattern: "git reflog exists *", decision: "allow" },
  { pattern: "git shortlog", decision: "allow" },
  { pattern: "git shortlog *", decision: "allow" },
  { pattern: "git whatchanged", decision: "allow" },
  { pattern: "git whatchanged *", decision: "allow" },
  { pattern: "git range-diff *", decision: "allow" },
  { pattern: "git cherry", decision: "allow" },
  { pattern: "git cherry *", decision: "allow" },
  { pattern: "git describe", decision: "allow" },
  { pattern: "git describe *", decision: "allow" },
  { pattern: "git name-rev *", decision: "allow" },
  { pattern: "git merge-tree *", decision: "allow" },
  { pattern: "git diff-tree *", decision: "allow" },
  { pattern: "git diff-files", decision: "allow" },
  { pattern: "git diff-files *", decision: "allow" },
  { pattern: "git show-branch", decision: "allow" },
  { pattern: "git show-branch *", decision: "allow" },
];

const defaultGitReadRules: Rule[] = [
  { pattern: "git status", decision: "allow" },
  { pattern: "git status *", decision: "allow" },
  { pattern: "git log", decision: "allow" },
  { pattern: "git log *", decision: "allow" },
  { pattern: "git diff", decision: "allow" },
  { pattern: "git diff *", decision: "allow" },
  { pattern: "git pull", decision: "allow" },
  { pattern: "git bisect *", decision: "allow" },
  { pattern: "git show *", decision: "allow" },
  { pattern: "git ls-files", decision: "allow" },
  { pattern: "git ls-files *", decision: "allow" },
  { pattern: "git rev-parse", decision: "allow" },
  { pattern: "git rev-parse *", decision: "allow" },
  { pattern: "git show-ref", decision: "allow" },
  { pattern: "git show-ref *", decision: "allow" },
  { pattern: "git merge-base *", decision: "allow" },
  { pattern: "git blame *", decision: "allow" },
  { pattern: "git rev-list", decision: "allow" },
  { pattern: "git rev-list *", decision: "allow" },
  { pattern: "git ls-tree *", decision: "allow" },
  { pattern: "git cat-file", decision: "allow" },
  { pattern: "git cat-file *", decision: "allow" },
  { pattern: "git for-each-ref", decision: "allow" },
  { pattern: "git for-each-ref *", decision: "allow" },
  { pattern: "git remote", decision: "allow" },
  { pattern: "git remote -v", decision: "allow" },
  { pattern: "git remote show *", decision: "allow" },
  { pattern: "git remote get-url *", decision: "allow" },
  { pattern: "git stash list", decision: "allow" },
  { pattern: "git stash list *", decision: "allow" },
  { pattern: "git stash show *", decision: "allow" },
  ...sharedGitReadRules,
];

export const defaultGitRules: Rule[] = [
  { pattern: "git *", decision: "ask" },

  ...defaultGitReadRules,
  { pattern: "git branch *", decision: "deny" },
  { pattern: "git rebase *", decision: "deny" },
  { pattern: "git switch *", decision: "deny" },
  { pattern: "git tag *", decision: "deny" },
  { pattern: "git commit *", decision: "deny" },
  { pattern: "git push *", decision: "deny" },
  { pattern: "git checkout *", decision: "deny" },
  { pattern: "git add *", decision: "deny" },
  { pattern: "git worktree *", decision: "deny" },

  { pattern: "git branch", decision: "allow" },
  { pattern: "git branch --show-current", decision: "allow" },
  { pattern: "git branch --list", decision: "allow" },
  { pattern: "git branch --list *", decision: "allow" },
  { pattern: "git branch --contains *", decision: "allow" },
  { pattern: "git branch --merged *", decision: "allow" },
  { pattern: "git branch --no-merged *", decision: "allow" },
  { pattern: "git branch --points-at *", decision: "allow" },
  { pattern: "git branch --all", decision: "allow" },
  { pattern: "git branch --remotes", decision: "allow" },
  { pattern: "git branch -a", decision: "allow" },
  { pattern: "git branch -r", decision: "allow" },
  { pattern: "git branch -v", decision: "allow" },
  { pattern: "git branch -vv", decision: "allow" },
  { pattern: "git branch -av", decision: "allow" },
  { pattern: "git branch -avv", decision: "allow" },
  { pattern: "git branch -rv", decision: "allow" },
  { pattern: "git branch -rvv", decision: "allow" },
  { pattern: "git tag", decision: "allow" },
  { pattern: "git tag --list", decision: "allow" },
  { pattern: "git tag --list *", decision: "allow" },
  { pattern: "git tag --contains *", decision: "allow" },
  { pattern: "git tag --merged *", decision: "allow" },
  { pattern: "git tag --no-merged *", decision: "allow" },
  { pattern: "git tag --points-at *", decision: "allow" },
  { pattern: "git tag -l", decision: "allow" },
  { pattern: "git tag -l *", decision: "allow" },
  { pattern: "git tag --sort*", decision: "allow" },
  { pattern: "git worktree list", decision: "allow" },
  { pattern: "git worktree list *", decision: "allow" },
];

/**
 * Git index/history/worktree mutation allows (`ruleset:git-commit`) for
 * `builtin:committer`. Appended after the default git denies, identical
 * patterns tie on specificity and resolve by composition order.
 */
export const gitCommitRules: Rule[] = [
  { pattern: "git add *", decision: "allow" },
  { pattern: "git commit", decision: "allow" },
  { pattern: "git commit *", decision: "allow" },
  { pattern: "git reset *", decision: "allow" },
  { pattern: "git restore *", decision: "allow" },
  { pattern: "git checkout *", decision: "allow" },
  { pattern: "git rebase *", decision: "allow" },
  { pattern: "git cherry-pick *", decision: "allow" },
  { pattern: "git worktree *", decision: "allow" },
  { pattern: "git rm *", decision: "allow" },
  { pattern: "git mv *", decision: "allow" },
];

/**
 * Ref mutation allows (`ruleset:git-refs`: push/branch/tag/switch) for
 * `builtin:git-full`.
 */
export const gitRefsRules: Rule[] = [
  { pattern: "git push", decision: "allow" },
  { pattern: "git push *", decision: "allow" },
  { pattern: "git branch *", decision: "allow" },
  { pattern: "git tag *", decision: "allow" },
  { pattern: "git switch *", decision: "allow" },
];

export const readOnlyGitRules: Rule[] = [
  { pattern: "git", decision: "allow" },
  { pattern: "git version", decision: "allow" },
  { pattern: "git help", decision: "allow" },
  { pattern: "git help *", decision: "allow" },
  { pattern: "git status", decision: "allow" },
  { pattern: "git status *", decision: "allow" },
  { pattern: "git log", decision: "allow" },
  { pattern: "git log *", decision: "allow" },
  { pattern: "git show", decision: "allow" },
  { pattern: "git show *", decision: "allow" },
  { pattern: "git diff", decision: "allow" },
  { pattern: "git diff *", decision: "allow" },
  { pattern: "git blame *", decision: "allow" },
  { pattern: "git annotate *", decision: "allow" },
  { pattern: "git rev-parse", decision: "allow" },
  { pattern: "git rev-parse *", decision: "allow" },
  { pattern: "git rev-list", decision: "allow" },
  { pattern: "git rev-list *", decision: "allow" },
  { pattern: "git show-ref", decision: "allow" },
  { pattern: "git show-ref *", decision: "allow" },
  { pattern: "git merge-base *", decision: "allow" },
  { pattern: "git ls-files", decision: "allow" },
  { pattern: "git ls-files *", decision: "allow" },
  { pattern: "git ls-tree *", decision: "allow" },
  { pattern: "git cat-file", decision: "allow" },
  { pattern: "git cat-file *", decision: "allow" },
  { pattern: "git for-each-ref", decision: "allow" },
  { pattern: "git for-each-ref *", decision: "allow" },
  { pattern: "git branch", decision: "allow" },
  { pattern: "git branch --show-current", decision: "allow" },
  { pattern: "git branch --list", decision: "allow" },
  { pattern: "git branch --list *", decision: "allow" },
  { pattern: "git branch --contains *", decision: "allow" },
  { pattern: "git branch --merged *", decision: "allow" },
  { pattern: "git branch --no-merged *", decision: "allow" },
  { pattern: "git branch --points-at *", decision: "allow" },
  { pattern: "git branch --all", decision: "allow" },
  { pattern: "git branch --remotes", decision: "allow" },
  { pattern: "git branch -a", decision: "allow" },
  { pattern: "git branch -r", decision: "allow" },
  { pattern: "git branch -v", decision: "allow" },
  { pattern: "git branch -vv", decision: "allow" },
  { pattern: "git branch -av", decision: "allow" },
  { pattern: "git branch -avv", decision: "allow" },
  { pattern: "git branch -rv", decision: "allow" },
  { pattern: "git branch -rvv", decision: "allow" },
  { pattern: "git tag", decision: "allow" },
  { pattern: "git tag --list", decision: "allow" },
  { pattern: "git tag --list *", decision: "allow" },
  { pattern: "git tag --contains *", decision: "allow" },
  { pattern: "git tag --merged *", decision: "allow" },
  { pattern: "git tag --no-merged *", decision: "allow" },
  { pattern: "git tag --points-at *", decision: "allow" },
  { pattern: "git tag --sort*", decision: "allow" },
  { pattern: "git tag -l", decision: "allow" },
  { pattern: "git tag -l *", decision: "allow" },
  { pattern: "git remote", decision: "allow" },
  { pattern: "git remote -v", decision: "allow" },
  { pattern: "git remote show *", decision: "allow" },
  { pattern: "git remote get-url *", decision: "allow" },
  { pattern: "git stash list", decision: "allow" },
  { pattern: "git stash list *", decision: "allow" },
  { pattern: "git stash show *", decision: "allow" },
  { pattern: "git submodule status", decision: "allow" },
  { pattern: "git submodule status *", decision: "allow" },
  { pattern: "git worktree list", decision: "allow" },
  { pattern: "git worktree list *", decision: "allow" },
  { pattern: "git sparse-checkout list", decision: "allow" },
  { pattern: "git count-objects", decision: "allow" },
  { pattern: "git count-objects *", decision: "allow" },
  { pattern: "git fsck", decision: "allow" },
  { pattern: "git fsck *", decision: "allow" },
  { pattern: "git symbolic-ref HEAD", decision: "allow" },
  { pattern: "git symbolic-ref --short HEAD", decision: "allow" },
  { pattern: "git verify-commit *", decision: "allow" },
  { pattern: "git verify-tag *", decision: "allow" },
  { pattern: "git diff-index *", decision: "allow" },
  ...sharedGitReadRules,
];
