import type { Rule } from "../policyHelpers";
import { defaultGuardRules } from "./guards";
import { defaultGitRules, readOnlyGitRules } from "./git";
import {
  npmMutationGuidance,
  packageManagerMutationDenials,
} from "./packageManagers";

export const defaultShellRules: Rule[] = [
  { pattern: "*", decision: "ask" },
  { pattern: "git *", decision: "ask" },

  ...defaultGitRules,
  { pattern: "git branch *", decision: "deny" },
  { pattern: "git rebase *", decision: "deny" },
  { pattern: "git switch *", decision: "deny" },
  { pattern: "git tag *", decision: "deny" },
  { pattern: "git commit *", decision: "deny" },
  { pattern: "git push *", decision: "deny" },
  { pattern: "git checkout *", decision: "deny" },
  { pattern: "git add *", decision: "deny" },
  { pattern: "git worktree *", decision: "deny" },

  { pattern: "git branch", decision: "allow" },
  { pattern: "git branch --show-current", decision: "allow" },
  { pattern: "git branch --list", decision: "allow" },
  { pattern: "git branch --list *", decision: "allow" },
  { pattern: "git branch --contains *", decision: "allow" },
  { pattern: "git branch --merged *", decision: "allow" },
  { pattern: "git branch --no-merged *", decision: "allow" },
  { pattern: "git branch --points-at *", decision: "allow" },
  { pattern: "git branch --all", decision: "allow" },
  { pattern: "git branch --remotes", decision: "allow" },
  { pattern: "git branch -a", decision: "allow" },
  { pattern: "git branch -r", decision: "allow" },
  { pattern: "git branch -v", decision: "allow" },
  { pattern: "git branch -vv", decision: "allow" },
  { pattern: "git branch -av", decision: "allow" },
  { pattern: "git branch -avv", decision: "allow" },
  { pattern: "git branch -rv", decision: "allow" },
  { pattern: "git branch -rvv", decision: "allow" },
  { pattern: "git tag", decision: "allow" },
  { pattern: "git tag --list", decision: "allow" },
  { pattern: "git tag --list *", decision: "allow" },
  { pattern: "git tag --contains *", decision: "allow" },
  { pattern: "git tag --merged *", decision: "allow" },
  { pattern: "git tag --no-merged *", decision: "allow" },
  { pattern: "git tag --points-at *", decision: "allow" },
  { pattern: "git tag -l", decision: "allow" },
  { pattern: "git tag -l *", decision: "allow" },
  { pattern: "git tag --sort*", decision: "allow" },
  { pattern: "git worktree list", decision: "allow" },
  { pattern: "git worktree list *", decision: "allow" },

  { pattern: "pwd", decision: "allow" },
  { pattern: "cd", decision: "allow" },
  {
    pattern: "printf",
    decision: "deny",
    guidance:
      'printing can reveal secrets. If you just want a separator use `echo "---"`',
  },
  {
    pattern: "echo",
    decision: "deny",
    guidance:
      'echo can reveal secrets. If you just want a separator use `echo "---"`',
  },
  { pattern: 'echo "---"', decision: "allow" },
  { pattern: "cd *", decision: "allow" },
  { pattern: "find *", decision: "allow" },
  { pattern: "cat", decision: "allow" },
  { pattern: "cat *", decision: "allow" },
  { pattern: "sort *", decision: "allow" },
  { pattern: "sort", decision: "allow" },
  { pattern: "sed", decision: "allow" },
  { pattern: "sed *", decision: "allow" },
  { pattern: "ls", decision: "allow" },
  { pattern: "ls *", decision: "allow" },
  { pattern: "wc", decision: "allow" },
  { pattern: "wc *", decision: "allow" },
  { pattern: "file", decision: "allow" },
  { pattern: "file *", decision: "allow" },
  { pattern: "head", decision: "allow" },
  { pattern: "head *", decision: "allow" },
  { pattern: "tail", decision: "allow" },
  { pattern: "tail *", decision: "allow" },
  { pattern: "rg *", decision: "allow" },
  { pattern: "ripgrep *", decision: "allow" },

  { pattern: "npm *", decision: "ask" },
  { pattern: "npm run *", decision: "allow" },
  { pattern: "npm test", decision: "allow" },
  { pattern: "npm test *", decision: "allow" },
  { pattern: "npm start", decision: "allow" },
  { pattern: "npm start *", decision: "allow" },
  { pattern: "npm stop", decision: "allow" },
  { pattern: "npm restart", decision: "allow" },
  { pattern: "npm ls", decision: "allow" },
  { pattern: "npm ls *", decision: "allow" },
  { pattern: "npm list", decision: "allow" },
  { pattern: "npm list *", decision: "allow" },
  { pattern: "npm view", decision: "allow" },
  { pattern: "npm view *", decision: "allow" },
  { pattern: "npm info", decision: "allow" },
  { pattern: "npm info *", decision: "allow" },
  { pattern: "npm show", decision: "allow" },
  { pattern: "npm show *", decision: "allow" },
  { pattern: "npm outdated", decision: "allow" },
  { pattern: "npm outdated *", decision: "allow" },
  { pattern: "npm audit", decision: "allow" },
  { pattern: "npm explain", decision: "allow" },
  { pattern: "npm explain *", decision: "allow" },
  { pattern: "npm why", decision: "allow" },
  { pattern: "npm why *", decision: "allow" },
  { pattern: "npm config get *", decision: "allow" },
  { pattern: "npm config list", decision: "allow" },
  { pattern: "npm prefix", decision: "allow" },
  { pattern: "npm root", decision: "allow" },
  { pattern: "npm doctor", decision: "allow" },
  { pattern: "npm help", decision: "allow" },
  { pattern: "npm help *", decision: "allow" },
  ...packageManagerMutationDenials("npm", [
    "install",
    "i",
    "add",
    "ci",
    "update",
    "uninstall",
    "remove",
    "rm",
    "publish",
    "link",
    "login",
    "logout",
    "token",
    "pkg set",
    "config set",
    "config delete",
    "audit fix",
  ]),
  { pattern: "npm version *", decision: "deny", guidance: npmMutationGuidance },

  { pattern: "pnpm *", decision: "ask" },
  { pattern: "pnpm run *", decision: "allow" },
  { pattern: "pnpm test", decision: "allow" },
  { pattern: "pnpm test *", decision: "allow" },
  { pattern: "pnpm start", decision: "allow" },
  { pattern: "pnpm ls", decision: "allow" },
  { pattern: "pnpm ls *", decision: "allow" },
  { pattern: "pnpm list", decision: "allow" },
  { pattern: "pnpm list *", decision: "allow" },
  { pattern: "pnpm outdated", decision: "allow" },
  { pattern: "pnpm outdated *", decision: "allow" },
  { pattern: "pnpm audit", decision: "allow" },
  { pattern: "pnpm why", decision: "allow" },
  { pattern: "pnpm why *", decision: "allow" },
  ...packageManagerMutationDenials("pnpm", [
    "add",
    "install",
    "i",
    "update",
    "remove",
    "rm",
    "uninstall",
    "publish",
    "dlx",
    "link",
  ]),
  {
    pattern: "pnpm audit --fix*",
    decision: "deny",
    guidance: npmMutationGuidance,
  },

  { pattern: "yarn *", decision: "ask" },
  { pattern: "yarn run *", decision: "allow" },
  { pattern: "yarn test", decision: "allow" },
  { pattern: "yarn test *", decision: "allow" },
  { pattern: "yarn start", decision: "allow" },
  { pattern: "yarn list", decision: "allow" },
  { pattern: "yarn list *", decision: "allow" },
  { pattern: "yarn info", decision: "allow" },
  { pattern: "yarn info *", decision: "allow" },
  { pattern: "yarn outdated", decision: "allow" },
  { pattern: "yarn why *", decision: "allow" },
  ...packageManagerMutationDenials("yarn", [
    "add",
    "install",
    "remove",
    "upgrade",
    "publish",
    "dlx",
    "link",
    "config set",
  ]),

  { pattern: "pip *", decision: "ask" },
  { pattern: "pip list", decision: "allow" },
  { pattern: "pip list *", decision: "allow" },
  { pattern: "pip show", decision: "allow" },
  { pattern: "pip show *", decision: "allow" },
  { pattern: "pip freeze", decision: "allow" },
  { pattern: "pip freeze *", decision: "allow" },
  ...packageManagerMutationDenials("pip", ["install", "uninstall"]),

  { pattern: "pip3 *", decision: "ask" },
  { pattern: "pip3 list", decision: "allow" },
  { pattern: "pip3 list *", decision: "allow" },
  { pattern: "pip3 show", decision: "allow" },
  { pattern: "pip3 show *", decision: "allow" },
  { pattern: "pip3 freeze", decision: "allow" },
  { pattern: "pip3 freeze *", decision: "allow" },
  ...packageManagerMutationDenials("pip3", ["install", "uninstall"]),

  { pattern: "uv *", decision: "ask" },
  { pattern: "uv pip list", decision: "allow" },
  { pattern: "uv pip list *", decision: "allow" },
  { pattern: "uv pip show", decision: "allow" },
  { pattern: "uv pip show *", decision: "allow" },
  { pattern: "uv pip freeze", decision: "allow" },
  { pattern: "uv pip freeze *", decision: "allow" },
  { pattern: "uv tree", decision: "allow" },
  { pattern: "uv tree *", decision: "allow" },
  ...packageManagerMutationDenials("uv", [
    "pip install",
    "pip uninstall",
    "add",
    "remove",
    "sync",
    "lock",
    "publish",
    "tool install",
  ]),

  { pattern: "cargo *", decision: "ask" },
  { pattern: "cargo build", decision: "allow" },
  { pattern: "cargo build *", decision: "allow" },
  { pattern: "cargo test", decision: "allow" },
  { pattern: "cargo test *", decision: "allow" },
  { pattern: "cargo check", decision: "allow" },
  { pattern: "cargo check *", decision: "allow" },
  { pattern: "cargo clippy", decision: "allow" },
  { pattern: "cargo clippy *", decision: "allow" },
  { pattern: "cargo doc", decision: "allow" },
  { pattern: "cargo doc *", decision: "allow" },
  ...packageManagerMutationDenials("cargo", [
    "install",
    "add",
    "remove",
    "uninstall",
    "publish",
  ]),

  { pattern: "gem *", decision: "ask" },
  { pattern: "gem list", decision: "allow" },
  { pattern: "gem list *", decision: "allow" },
  ...packageManagerMutationDenials("gem", ["install", "uninstall", "push"]),

  { pattern: "bundle *", decision: "ask" },
  { pattern: "bundle list", decision: "allow" },
  { pattern: "bundle list *", decision: "allow" },
  ...packageManagerMutationDenials("bundle", ["install", "update", "add"]),

  { pattern: "composer *", decision: "ask" },
  { pattern: "composer show", decision: "allow" },
  { pattern: "composer show *", decision: "allow" },
  ...packageManagerMutationDenials("composer", [
    "install",
    "update",
    "require",
    "remove",
  ]),

  {
    pattern: "npm exec",
    decision: "deny",
    guidance:
      "Do not run one-off binaries with npm exec. Use the package.json scripts defined for this repository instead.",
    alternatives: [
      "npm run test",
      "npm run test:watch",
      "npm run check:all",
      "npm run check:prettier",
      "npm run fix:prettier",
    ],
  },
  {
    pattern: "npm exec *",
    decision: "deny",
    guidance:
      "Do not run one-off binaries with npm exec. Use the package.json scripts defined for this repository instead.",
    alternatives: [
      "npm run test",
      "npm run test:watch",
      "npm run check:all",
      "npm run check:prettier",
      "npm run fix:prettier",
    ],
  },
  { pattern: "go *", decision: "allow" },
  ...packageManagerMutationDenials("go", ["install", "get"]),
  { pattern: "true", decision: "allow" },
  { pattern: "rg *", decision: "allow" },
  { pattern: "ripgrep *", decision: "allow" },
  { pattern: "terraform fmt *", decision: "allow" },
  { pattern: "terraform validate", decision: "allow" },
  { pattern: "terraform validate *", decision: "allow" },
  { pattern: "terraform -chdir=* validate", decision: "allow" },
  { pattern: "terraform -chdir=* validate *", decision: "allow" },
  { pattern: "nl", decision: "allow" },
  { pattern: "nl *", decision: "allow" },

  ...defaultGuardRules,
];

const readOnlyGuardRules: Rule[] = [
  {
    pattern: "git branch -d*",
    decision: "deny",
    guidance: "Branch deletion is not allowed in the read-only profile.",
  },
  {
    pattern: "git branch -D*",
    decision: "deny",
    guidance: "Branch deletion is not allowed in the read-only profile.",
  },
  {
    pattern: "git branch -m*",
    decision: "deny",
    guidance: "Branch renames are not allowed in the read-only profile.",
  },
  {
    pattern: "git tag -d*",
    decision: "deny",
    guidance: "Tag deletion is not allowed in the read-only profile.",
  },
  {
    pattern: "git tag -f*",
    decision: "deny",
    guidance: "Tag rewrites are not allowed in the read-only profile.",
  },
  {
    pattern: "git remote add*",
    decision: "deny",
    guidance: "Remote creation is not allowed in the read-only profile.",
  },
  {
    pattern: "git remote remove*",
    decision: "deny",
    guidance: "Remote removal is not allowed in the read-only profile.",
  },
  {
    pattern: "git remote rename*",
    decision: "deny",
    guidance: "Remote renames are not allowed in the read-only profile.",
  },
  {
    pattern: "git remote set-url*",
    decision: "deny",
    guidance: "Remote URL changes are not allowed in the read-only profile.",
  },
  {
    pattern: "git worktree add*",
    decision: "deny",
    guidance: "Worktree creation is not allowed in the read-only profile.",
  },
  {
    pattern: "git worktree remove*",
    decision: "deny",
    guidance: "Worktree removal is not allowed in the read-only profile.",
  },
  {
    pattern: "git worktree move*",
    decision: "deny",
    guidance: "Worktree moves are not allowed in the read-only profile.",
  },
  {
    pattern: "git update-ref*",
    decision: "deny",
    guidance: "Reference updates are not allowed in the read-only profile.",
  },
  {
    pattern: "git symbolic-ref*",
    decision: "deny",
    guidance: "Reference updates are not allowed in the read-only profile.",
  },
  {
    pattern: "git checkout -b*",
    decision: "deny",
    guidance: "Branch creation is not allowed in the read-only profile.",
  },
  {
    pattern: "git switch -c*",
    decision: "deny",
    guidance: "Branch creation is not allowed in the read-only profile.",
  },
  {
    pattern: "git merge *",
    decision: "deny",
    guidance: "Merges are not allowed in the read-only profile.",
  },
  {
    pattern: "git rebase *",
    decision: "deny",
    guidance: "Rebases are not allowed in the read-only profile.",
  },
  {
    pattern: "git reset *",
    decision: "deny",
    guidance: "History rewrites are not allowed in the read-only profile.",
  },
  {
    pattern: "git commit *",
    decision: "deny",
    guidance: "Commits are not allowed in the read-only profile.",
  },
  {
    pattern: "git push *",
    decision: "deny",
    guidance: "Pushes are not allowed in the read-only profile.",
  },
  {
    pattern: "git stash push*",
    decision: "deny",
    guidance: "Stash writes are not allowed in the read-only profile.",
  },
  {
    pattern: "git stash drop*",
    decision: "deny",
    guidance: "Stash writes are not allowed in the read-only profile.",
  },
  {
    pattern: "git stash pop*",
    decision: "deny",
    guidance: "Stash writes are not allowed in the read-only profile.",
  },
];

export const readOnlyShellRules: Rule[] = [
  {
    pattern: "*",
    decision: "deny",
    guidance:
      "The read-only profile only permits inspection commands and non-destructive git history queries.",
  },
  { pattern: "pwd", decision: "allow" },
  { pattern: "cd", decision: "allow" },
  { pattern: "cd *", decision: "allow" },
  { pattern: "ls", decision: "allow" },
  { pattern: "ls *", decision: "allow" },
  { pattern: "find *", decision: "allow" },
  { pattern: "cat", decision: "allow" },
  { pattern: "cat *", decision: "allow" },
  { pattern: "sed", decision: "allow" },
  { pattern: "sed *", decision: "allow" },
  { pattern: "sort", decision: "allow" },
  { pattern: "sort *", decision: "allow" },
  { pattern: "rg *", decision: "allow" },
  { pattern: "ripgrep *", decision: "allow" },
  { pattern: "head", decision: "allow" },
  { pattern: "head *", decision: "allow" },
  { pattern: "tail", decision: "allow" },
  { pattern: "tail *", decision: "allow" },
  { pattern: "nl", decision: "allow" },
  { pattern: "nl *", decision: "allow" },
  { pattern: "wc", decision: "allow" },
  { pattern: "wc *", decision: "allow" },
  { pattern: "file", decision: "allow" },
  { pattern: "file *", decision: "allow" },
  ...readOnlyGitRules,
  ...readOnlyGuardRules,
  // Compose the shared guard set last so its specificity-tie winners remain
  // the final authority for destructive/unsafe shell operands.
  ...defaultGuardRules,
];
